gw: http://localhost:8080/api/v1

server:
    port: 8060
spring:
    datasource:
        password: test
        url: jdbc:postgresql://localhost:5431/rentals
        username: program
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

